from .root import MonnifyAPI


class Refund(MonnifyAPI):
    def __init__(self):
        super().__init__()

    @classmethod
    def initiate_refund(cls, **kwargs):
        """
        Initiate Refund
        This endpoint allows you to Initiate a refund.

        Args:
            transactionReference (str): Unique identifier for the transaction generated by Monnify.
            refundAmount (float): Amount to refund.
            refundReference (str): Unique identifier for the transaction refund generated by the merchant.
            refundReason (str): A note describing reason why this transaction is being refunded.
            customerNote (str): This field serves as a narration in credit to the customer's bank account.
            destinationAccountNumber (str): The account number to be refunded
            destinationBankCode (str): The bank code for the destinationAccountNumber.

        Returns:
            dict: JSON response from Monnify API
        """

        return cls.make_request("/api/v1/refunds/initiate-refund", "POST", data=kwargs)

    @classmethod
    def get_refund_status(cls, refundReference):
        """
        Get Refund Status
        This endpoint returns the status of an initiated refund.

        Args:
            refundReference (str): The refund reference used for the refund.

        Returns:
            dict: JSON response from Monnify API
        """
        return cls.make_request(f"/api/v1/refunds/{refundReference}", "GET")

    @classmethod
    def get_all_refunds(cls, page=0, size=10):
        """
        Get All Refunds
        This endpoint returns the list of all refunds available on your integration.

        Args:
            page (int, optional): An integer specifying the page of transactions to be retrieved. Page number starts from 0. Defaults to 0.
            size (int, optional): An integer specifying the size of transactions to be returned per page. Defaults to 10.

        Returns:
            dict: JSON response from Monnify API
        """
        params = {"page": page, "size": size}

        return cls.make_request("/api/v1/refunds", "GET", params=params)
